# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dummy": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Hansjoerg Wingeier.github.io/SA_CAS_BGD/"

git_url = "https://github.com/Hansjoerg Wingeier/SA_CAS_BGD/tree/master/"

def custom_doc_links(name): return None
