# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_spark_session": "00_00_core.ipynb",
         "get_directory_size": "00_00_core.ipynb",
         "get_size_format": "00_00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://HansjoergW.github.io/bfh_cas_bgd_fs2020_sa/"

git_url = "https://github.com/HansjoergW/bfh_cas_bgd_fs2020_sa/tree/master/"

def custom_doc_links(name): return None
